name: Build Executables

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output: xadrez
          - os: windows-latest
            output: xadrez.exe
          - os: macos-latest
            output: xadrez
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile on ${{ matrix.os }}
      run: gcc menu.c jogo.c jogadasvalidas.c -o ${{ matrix.output }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: xadrez-${{ matrix.os }}
        path: ${{ matrix.output }}